let produtos = [
    {
        id: 0,
        name: 'Celular',
        img: 'images/celular.jpg',
        description: 'Smartphone HP A22 128GB 4G Wi-Fi Tela 6.4 Dual Chip 4GB RAM',
        price: 2500.00,
        juros: '12x de R$208,33 sem juros no cartão',
    },
    {
        id: 1,
        name: 'Geladeira',
        img: 'images/geladeira.jpg',
        description: 'Geladeira/Refrigerador Brastemp Frost Free BRM44 375 Litros - Evox - 220v',
        price: 7500.00,
        juros: '12x de R$625 sem juros no cartão',
    },
    {
        id: 2,
        name: 'Guarda-Roupas',
        img: 'images/guarda-roupas.jpg',
        description: 'Guarda Roupa Casal 6 Portas 2 Gavetas Paris Siena Móveis',
        price: 5262.00,
        juros: '12x de R$438,50 sem juros no cartão',
    },
    {
        id: 3,
        name: 'Microondas',
        img: 'images/microondas.jpg',
        description: 'Forno micro-ondas Electrolux MTD30 20 litros 220v',
        price: 1500.00,
        juros: '12x de R$125,00 sem juros no cartão',
    },
    {
        id: 4,
        name: 'Máquina de Lavar Roupas',
        img: 'images/maquina-lavar.jpg',
        description: 'Máquina de Lavar Brastemp 12Kg BWK12 com Ciclo Antibolinha - 220v',
        price: 1899.99,
        juros: '12x de R$158,32 sem juros no cartão',
    },
    {
        id: 5,
        name: 'Televisao Samsung',
        img: 'images/televisao.jpg',
        description: 'Smart TV LED 32 HD Samsung TL020 Conversor Digital Externo 3 hdmi 2 USB Wi-Fi',
        price: 1366.20,
        juros: '12x de R$113,85 sem juros no cartão',
    },
    {
        id: 6,
        name: 'Sofá',
        img: 'images/sofa.jpg',
        description: 'Sofá 3 Lugares Retrátil e Reclinável Cama inBox Compact 1,80m Velusoft Cinza',
        price:  899.00,
        juros: '12x de R$74,91 sem juros no cartão',
    },
    {
        id: 7,
        name: 'Mesa de Jantar',
        img: 'images/mesa-jantar.jpg',
        description: 'Mesa de Jantar Unique com 4 Cadeiras Napoli Imbuia e Off White - Viero',
        price: 569.89,
        juros: '12x de R$47,49 sem juros no cartão',
    },

]